### ISSUE TITLE
Proto file registration panic on startup

### ISSUE THREAD

**Issue by torkelrogstad** [lightninglabs/faraday#108]
I'm integrating Faraday into an application that communicates with gRPC, and I'm running into issues when importing the generated Faraday Go code: `panic: proto: file "rpc.proto" is already registered`. See this related issue on the golang/protobuf tracker: https://github.com/golang/protobuf/issues/1122. 

This is the line that panics: 
https://github.com/lightninglabs/faraday/blob/master/frdrpc/rpc.pb.go#L1630

I'm no expert on technicalities of Protobuf/gRPC, but I see that other Go sources I'm using that's compiled from Proto files don't have the problematic reigstration function. These Go sources are compiled with a newer gRPC stack, specifically `protoc-gen-go` 1.25.0 and `protoc` 3.13.0. Could it be that compiling the Faraday Go sources with the newer gRPC stack would solve this?

The only real workaround right now is setting an environment variable, and I would have to make sure that this environment variable is properly set on all developer machines, production machines and CI systems. Sounds like a hassle...

**Comment by guggero** [comment]
I think the main issue here is that the `rpc.proto` has the same name as `lnd`'s `rpc.proto`. A simple fix would be to rename it. Also updating the `grpc` library to the same version we now use in `lnd` should turn the panic into a warning.
@carlaKC do you have time to look at this?

**Comment by carlaKC** [comment]
Yeah will pick this up!

**Comment by carlaKC** [comment]
Yeah will pick this up!

**Comment by torkelrogstad** [comment]
Closed in https://github.com/lightninglabs/faraday/pull/110
