### ISSUE TITLE
404 link to Harmony Reporting Standard

### ISSUE THREAD

**Issue by zanepocock** [lightninglabs/faraday#138]
The [Harmony Reporting Standard](https://github.com/picksco/harmony) repo has been removed by [Picks & Shovels](https://github.com/picksco).

Linked to from this repo [here](https://github.com/lightninglabs/faraday/blob/f953eeaa9ef2fe2f88f94c01da6bdd231657ceb5/docs/accounting.md) and from Lightning Labs' docs [here](https://github.com/lightninglabs/docs.lightning.engineering/blob/7cde8a91f98544b1350f03a95cd8272841935397/docs/faraday/accounting.md).

I found @alexbosworth 's fork [here](https://github.com/alexbosworth/harmony) but it hasn't been updated since 2018 so there might be a more up-to-date copy out there somewhere.

**Comment by alexbosworth** [comment]
Potentially @mg0716 has a copy? Yes this was a 3rd party standard it wasn't defined by Lightning Labs
