### ISSUE TITLE
tls.cert path doesn't work

### ISSUE THREAD

**Issue by STEMr42** [lightninglabs/faraday#141]
**Expected behavior**

Using the same tls.cert path as lncli commands should not error

Setting --lnd.tlscertpath={path to lnd cert} produces "no such file or directory"

**To reproduce**

OS X 11.4
Build LND from source
Build Faraday from source

Start Faraday w/ 
`./faraday                                                   \
--lnd.macaroonpath={full path to lnd's readonly.macaroon}   \
--lnd.tlscertpath={path to lnd cert}                        \
--lnd.rpcserver={host:port of lnd's rpcserver}`

moving the tls.cert to ~/Library/Application Support/Lnd and using --lnd.tlscertpath="" resolves the issue

**Comment by guggero** [comment]
Could this be a problem with the space in `Application Support`? Did you try using double quotes around the full path?

**Comment by STEMr42** [comment]
> 

This works:
`lncli --rpcserver ip:port --macaroonpath ~/.bos/node/get.macaroon --tlscertpath ~/.bos/node/tls.cert getinfo`

This give error:
`faraday --lnd.rpcserver=ip:port --lnd.macaroonpath=~/.bos/node/get.macaroon --lnd.tlscertpath=~/.bos/node/tls.cert`
`Error starting faraday: cannot connect to lightning services: unable to get tls creds: open ~/.bos/node/tls.cert: no such file or directory%`

Moving the same cert to ~/Library/Application Support/Lnd and using --lnd.tlscertpath="" makes it work

**Comment by guggero** [comment]
Aah, I found the issue in the code. Going to create a fix for it. Essentially, the code that turns `~` into `/Users/<your_user>` is missing.
So as a workaround until the PR is in, try specifying a full, absolute path (with double quotes if there are spaces in there).
