### ISSUE TITLE
Can't Faraday be integrated with LND?

### ISSUE THREAD

**Issue by saubyk** [lightninglabs/faraday#18]
This is more of a question, than an issue.

It will be super convenient if Faraday is an integrated solution with LND.
Running multiple servers is challenge for building an integrated UI solution. With Loopd and now Faraday, the list of servers required to run lightning node operations is ever growing.

Or, if your plan is to enable integration with other lightning implementations like Eclair or C-Lightning, then it may make sense to keep it as a separate server.

**Comment by carlaKC** [comment]
This is certainly something we are looking into! We want it to be as easy as possible for operators and applications to run the lnd/loop/faraday stack. 

Faraday will remain decoupled from lnd for a few reasons. Having a separate tool allows users who don't want this additional functionality to use lnd as is, and on the development side of things it allows us to iterate more quickly. However, we also see the need for an integrated solution, so watch this space!
