### ISSUE TITLE
add support for --version flag in faraday and `frcli version`

### ISSUE THREAD

**Issue by githorray** [lightninglabs/faraday#57]
`frcli version` like `lncli version` would be really nice.

https://github.com/lightningnetwork/lnd/commit/f93a8ab7d085d7216e20f8a4c71749d281750b24

$ faraday --version
unknown flag `version'
2020-06-27 14:11:32.019 [INF] GVNR: Error starting faraday: error loading config: unknown flag `version'
$ frcli --version
frcli version 0.2.0-alpha commit=v0.2.0-alpha-31-g81e9e530e8c1361d428baab83cbf2f4aa9da7f66
$ frcli version
No help topic for 'version'

**Comment by carlaKC** [comment]
PR up for adding a version flag to the faraday binary 👍 

You can already get version using frcli if you run `frcli --version`

**Comment by githorray** [comment]
Works great. Thanks!

**Comment by carlaKC** [comment]
> Works great. Thanks!

Awesome! Keep the feature requests coming, it's really useful to know how we can help all the node operators out there 🚀
