### ISSUE TITLE
nodereport: file not found (TLS?)

### ISSUE THREAD

**Issue by carlaKC** [lightninglabs/faraday#78]
Copying across from #67 made by @githorray. 

Updated to the latest commit. Getting a new error:
```
$ frcli --version
frcli version 0.2.0-alpha commit=v0.2.0-alpha-90-g2415b5d866838880f7ddc0f57a79e3c9e589dbda
$ frcli nodereport
[frcli] open : no such file or directory
```

Running on mainnet.

**Comment by carlaKC** [comment]
@githorray could you try updating to `fc685e9` and check whether you get `unable to read tls cert (path: ?): no such file or directory"`?

Also is it possible that you are running an older version of faraday/frcli? It could be that the cert was not created. 

If you look in the app dir, is there a cert there? In `~/.faraday/mainnet/` or `Mac: /Users/{username}/Library/ApplicationSupport/Faraday/mainnet/` for mac?

**Comment by githorray** [comment]
`~/.faraday/mainnet$ ls
tls.cert  tls.key
~/.faraday/mainnet$ frcli audit
[frcli] unable to read tls cert (path: ): open : no such file or directory`

**Comment by guggero** [comment]
Oops, I think that is a bug I introduced with the TLS change. Fix is incoming.

**Comment by githorray** [comment]
Thanks, It is working now.
