### ISSUE TITLE
Don't require all macaroons to use Faraday

### ISSUE THREAD

**Issue by gkrizek** [lightninglabs/faraday#84]
Currently users are required to specify a directory for LND's macaroons with `--lnd.macaroondir`. This can be problematic or annoying if you aren't running Faraday on the same server that's running LND. I would suggest the ability to use a single macaroon (like `admin.macaroon`) to make it easy to use. Eventually once the macaroon baking changes land in LND we could even bake a macaroon specific for Faraday.

**Comment by junderw** [comment]
Not only should it be single macaroon, but I think you should mention in the README the bare minimum permissions needed, and allow for a custom macaroon (maybe even make a PR to lnd to auto-generate a faraday compatible minimum perms macaroon)

**Comment by guggero** [comment]
> You don't need to specify the `admin.macaroon`, that was just documented in an unfortunate way. Faraday should work if you just use `--lnd.macaroonpath=path/to/readonly.macaroon`.

Okay, I was wrong. I just looked how we use the `lndclient` in Faraday but forgot about the fact that the macaroon service in the `lndclient` requires to derive a shared secret to get a password for the macaroon DB. So the readonly macaroon isn't quite enough, you also need the `signer:generate` permission (or `uri:/signrpc.Signer/DeriveSharedKey`).
I'm going to create a PR to document this.

**Comment by guggero** [comment]
@junderw see https://github.com/lightninglabs/faraday/releases/tag/v0.2.11-alpha and the updated README file that now documents the exact permissions a macaroon needs.
