### ISSUE TITLE
panic if no timestamps are provided to ExchangeRate

### ISSUE THREAD

**Issue by torkelrogstad** [lightninglabs/faraday#86]
This line panics if no timestamps are given to ExchangeRate:

https://github.com/lightninglabs/faraday/blob/e5af3120fcf7309b7d3da25f5fe112f7474d3a4f/frdrpc/exchange_rate.go#L78

IMO it would be better to return an error here.

Edit:

I had a slight brain fart, meant the exchange rate endpoint and not the node audit endpoint.

**Comment by carlaKC** [comment]
Thanks for the issue, fix is up!
