### ISSUE TITLE
About RPC over HTTP and *.proto

### ISSUE THREAD

**Issue by LukasRada** [lightninglabs/faraday#97]
Why was RPC over HTTP chosen in proto files?

I ask because I'm not able to connect to faraday with generated client. I tried C# and also JavaScript. And I tried same way as it is described here: https://github.com/lightningnetwork/lnd/blob/master/docs/grpc/javascript.md but of course with proto for faraday.

Exception is thrown on any RPC method call. E.g.

```javascript
client.ChannelInsights({}, new Metadata(), {}, function (response) {
	console.log(response)
})
```

For JS the error is:
![image](https://user-images.githubusercontent.com/7394177/100391133-d382e100-3032-11eb-9022-7c36a0183594.png)

For C# the error is:
![image](https://user-images.githubusercontent.com/7394177/100391109-c534c500-3032-11eb-9fbc-ac699ce18acc.png)

And it is not connectivity issue because from client (my PC) I can see opened port 8465:
![image](https://user-images.githubusercontent.com/7394177/100391520-fcf03c80-3033-11eb-8e1a-a52e774af87b.png)

Or if I'm using proto files incorrectly then please show me how to generate client in languages such as JS or C#. Thank you.

**Comment by guggero** [comment]
This should work the same way as in lnd. Can you post the full JS code, especially the part where you load the TLS certificate and create the connection?

**Comment by LukasRada** [comment]
It is in TypeScript but TS is compiled into JS anyway.
```typescript
import { credentials, Metadata, loadPackageDefinition } from 'grpc';
import * as fs from 'fs';
import Description from './src-gen/grpc-node'
import * as protoLoader from '@grpc/proto-loader';

process.env.GRPC_SSL_CIPHER_SUITES = 'HIGH+ECDSA'

const loaderOptions = {
	keepCase: true,
	longs: String,
	enums: String,
	defaults: true,
	oneofs: true
};

const packageDefinition = protoLoader.loadSync('faraday.proto', loaderOptions);

const macaroonFile = fs.readFileSync('faraday.macaroon');
const macaroon = macaroonFile.toString('hex');

const cert = fs.readFileSync("tls.cert");
const sslCreds = credentials.createSsl(cert);

const macaroonCredenetials = credentials.createFromMetadataGenerator(function (_, callback) {
	const metadata = new Metadata()
	metadata.add("macaroon", macaroon)
	callback(null, metadata)
})

const combinedCredentials = credentials.combineChannelCredentials(sslCreds, macaroonCredenetials);

const descriptor = loadPackageDefinition(packageDefinition) as Description

const client = new descriptor.frdrpc.FaradayServer("IP:PORT", combinedCredentials);

client.ChannelInsights({}, new Metadata(), {}, function (response) {
	console.log(response)
})
```

I can prepare repo with my solution, if you wish, so you can see the behavior.

**Comment by guggero** [comment]
Sorry for the delay on this. I just tried this myself and ran into the same error.
Debugging this a bit further (running `GRPC_VERBOSITY=DEBUG node index.js`), I found out it's a problem in the `grpc` NodeJS library:
`D1130 11:16:11.730372465   18690 security_handshaker.cc:176] Security handshake failed: {"created":"@1606731371.730356864","description":"Cannot check peer: missing selected ALPN property.","file":"../deps/grpc/src/core/lib/security/security_connector/ssl_utils.cc","file_line":118}`

I think we've run into this as well somewhere, but I don't know if we ever found a fix for it. Will see if I can find out more.

**Comment by mrfelton** [comment]
c# client has the same issue.

**Comment by mrfelton** [comment]
I tried switching from `Grpc.Core` to `Grpc.Net.Client` in an attempt to get this working but no joy. With that client I get:

> Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server offers only version fallback

I also tried upgrading faraday's grpc server to `google.golang.org/grpc v1.35.0` but also no joy.

Something seems up with the faraday gRpc setup because the exact same code works fine with the lnd grpc server, with both  `Grpc.Core` and `Grpc.Net.Client` but in neither case can I connect to the Faraday gRPC interface.

**Comment by guggero** [comment]
Thank you for further investigating on this!
The hint that it works with the same version on `lnd` but doesn't on `faraday` was what gave me the idea what the problem could be.
Was able to reproduce the error and then fix it by switching over TLS handling to gRPC instead of using the default library's TLS listener: #106.
